/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CrmSprintComercialRouteImport } from './routes/crm.sprint-comercial'
import { Route as CrmServicosRouteImport } from './routes/crm.servicos'
import { Route as CrmFluxoVendedorRouteImport } from './routes/crm.fluxo-vendedor'
import { Route as CrmAgendaRouteImport } from './routes/crm.agenda'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmSprintComercialRoute = CrmSprintComercialRouteImport.update({
  id: '/sprint-comercial',
  path: '/sprint-comercial',
  getParentRoute: () => CrmRoute,
} as any)
const CrmServicosRoute = CrmServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => CrmRoute,
} as any)
const CrmFluxoVendedorRoute = CrmFluxoVendedorRouteImport.update({
  id: '/fluxo-vendedor',
  path: '/fluxo-vendedor',
  getParentRoute: () => CrmRoute,
} as any)
const CrmAgendaRoute = CrmAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => CrmRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/crm': typeof CrmRouteWithChildren
  '/login': typeof LoginRoute
  '/crm/agenda': typeof CrmAgendaRoute
  '/crm/fluxo-vendedor': typeof CrmFluxoVendedorRoute
  '/crm/servicos': typeof CrmServicosRoute
  '/crm/sprint-comercial': typeof CrmSprintComercialRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/crm': typeof CrmRouteWithChildren
  '/login': typeof LoginRoute
  '/crm/agenda': typeof CrmAgendaRoute
  '/crm/fluxo-vendedor': typeof CrmFluxoVendedorRoute
  '/crm/servicos': typeof CrmServicosRoute
  '/crm/sprint-comercial': typeof CrmSprintComercialRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/crm': typeof CrmRouteWithChildren
  '/login': typeof LoginRoute
  '/crm/agenda': typeof CrmAgendaRoute
  '/crm/fluxo-vendedor': typeof CrmFluxoVendedorRoute
  '/crm/servicos': typeof CrmServicosRoute
  '/crm/sprint-comercial': typeof CrmSprintComercialRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/crm'
    | '/login'
    | '/crm/agenda'
    | '/crm/fluxo-vendedor'
    | '/crm/servicos'
    | '/crm/sprint-comercial'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/crm'
    | '/login'
    | '/crm/agenda'
    | '/crm/fluxo-vendedor'
    | '/crm/servicos'
    | '/crm/sprint-comercial'
  id:
    | '__root__'
    | '/'
    | '/crm'
    | '/login'
    | '/crm/agenda'
    | '/crm/fluxo-vendedor'
    | '/crm/servicos'
    | '/crm/sprint-comercial'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CrmRoute: typeof CrmRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/sprint-comercial': {
      id: '/crm/sprint-comercial'
      path: '/sprint-comercial'
      fullPath: '/crm/sprint-comercial'
      preLoaderRoute: typeof CrmSprintComercialRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/servicos': {
      id: '/crm/servicos'
      path: '/servicos'
      fullPath: '/crm/servicos'
      preLoaderRoute: typeof CrmServicosRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/fluxo-vendedor': {
      id: '/crm/fluxo-vendedor'
      path: '/fluxo-vendedor'
      fullPath: '/crm/fluxo-vendedor'
      preLoaderRoute: typeof CrmFluxoVendedorRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/agenda': {
      id: '/crm/agenda'
      path: '/agenda'
      fullPath: '/crm/agenda'
      preLoaderRoute: typeof CrmAgendaRouteImport
      parentRoute: typeof CrmRoute
    }
  }
}

interface CrmRouteChildren {
  CrmAgendaRoute: typeof CrmAgendaRoute
  CrmFluxoVendedorRoute: typeof CrmFluxoVendedorRoute
  CrmServicosRoute: typeof CrmServicosRoute
  CrmSprintComercialRoute: typeof CrmSprintComercialRoute
}

const CrmRouteChildren: CrmRouteChildren = {
  CrmAgendaRoute: CrmAgendaRoute,
  CrmFluxoVendedorRoute: CrmFluxoVendedorRoute,
  CrmServicosRoute: CrmServicosRoute,
  CrmSprintComercialRoute: CrmSprintComercialRoute,
}

const CrmRouteWithChildren = CrmRoute._addFileChildren(CrmRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CrmRoute: CrmRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
